[project]
name = "mini-store"
version = "0.5.0"
description = "Terminal game"
readme = "README.md"
authors = [
    { name = "Lynx20wz", email = "maks20wz@gmail.com" },
    { name = "MrIcantYt", email = "icant@example.com" }
]
requires-python = "==3.13.6"
dependencies = [
    "colorama>=0.4.6",
    "cryptography>=50.0.2",
]


[tool.ruff]
indent-width = 4
line-length = 80

[tool.ruff.lint]
ignore = ['EXE002']

[tool.ruff.format]
indent-style = "space"
quote-style = "single"

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]
