[project]
name = "mini-store"
version = "0.5.0"
description = "Terminal game"
readme = "README.md"
authors = [
    { name = "Lynx20wz", email = "maks20wz@gmail.com" },
    { name = "MrIcantYt", email = "icant@example.com" }
]
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
]

[project.scripts]
mini-store = "mini_store:main"

[tool.ruff]
ignore = ['EXE002']
line-length = 100
indent-width = 4

[tool.ruff.format]
indent-style = "space"
quote-style = "single"
